sudo: required
language: python
services:
  - docker
python:
  - "3.8"
before_script:
  - docker-compose build
script:
  - docker-compose run --rm web flake8 . && docker-compose run --rm web python manage.py test
after_script:
  - docker-compose run codecov
notifications:
  email: false

cache:
  pip: true
