site_name: locuss-backend
site_description: Backend of the Locuss flashcard app
repo_url: https://github.com/ClemSau/locuss-backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/ClemSau">ClemSau</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
