# Generated by Django 3.0.7 on 2020-07-26 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front_text', models.CharField(max_length=180)),
                ('back_text', models.CharField(max_length=180)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
